export const nbaTeams = {
  "Atlanta Hawks": {
    logo: "../images/logos/Hawks.svg",
    primaryColor: "#E03A3E",
    secondaryColor: "#C1D32F",
    tertiaryColor: "#26282A",
  },
  "Boston Celtics": {
    logo: "../images/logos/Celtics.svg",
    primaryColor: "#008348",
    secondaryColor: "#BB9753",
    tertiaryColor: "#BA9653",
  },
  "Brooklyn Nets": {
    logo: "../images/logos/Nets.svg",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    tertiaryColor: "#C6CED4",
  },
  "Charlotte Hornets": {
    logo: "../images/logos/Hornets.svg",
    primaryColor: "#1D1160",
    secondaryColor: "#00788C",
    tertiaryColor: "#A1A1A4",
  },
  "Chicago Bulls": {
    logo: "../images/logos/Bulls.svg",
    primaryColor: "#CE1141",
    secondaryColor: "#000000",
    tertiaryColor: "#B4975A",
  },
  "Cleveland Cavaliers": {
    logo: "../images/logos/Cavaliers.svg",
    primaryColor: "#6F263D",
    secondaryColor: "#FFB81C",
    tertiaryColor: "#041E42",
  },
  "Dallas Mavericks": {
    logo: "../images/logos/Mavericks.svg",
    primaryColor: "#007DC5",
    secondaryColor: "#C4CED3",
    tertiaryColor: "#000000",
  },
  "Denver Nuggets": {
    logo: "../images/logos/Nuggets.svg",
    primaryColor: "#0E2240",
    secondaryColor: "#FEC524",
    tertiaryColor: "#8B2131",
  },
  "Detroit Pistons": {
    logo: "../images/logos/Pistons.svg",
    primaryColor: "#C8102E",
    secondaryColor: "#1D428A",
    tertiaryColor: "#C6CED4",
  },
  "Golden State Warriors": {
    logo: "../images/logos/Warriors.svg",
    primaryColor: "#1D428A",
    secondaryColor: "#FFC72C",
    tertiaryColor: "#26282A",
  },
  "Houston Rockets": {
    logo: "../images/logos/Rockets.svg",
    primaryColor: "#CE1141",
    secondaryColor: "#000000",
    tertiaryColor: "#C4CED3",
  },
  "Indiana Pacers": {
    logo: "../images/logos/Pacers.svg",
    primaryColor: "#002D62",
    secondaryColor: "#FDBB30",
    tertiaryColor: "#BEC0C2",
  },
  "Milwaukee Bucks": {
    logo: "../images/logos/Bucks.svg",
    primaryColor: "#00471B",
    secondaryColor: "#F0EBD2",
    tertiaryColor: "#0077C0",
  },

  "Los Angeles Clippers": {
    logo: "../images/logos/Clippers.svg",
    primaryColor: "#1d428a",
    secondaryColor: "#c8102e",
    thirdColor: "#ffffff",
  },
  "Los Angeles Lakers": {
    logo: "../images/logos/Lakers.svg",
    primaryColor: "#552583",
    secondaryColor: "#fdb927",
    thirdColor: "#ffffff",
  },
  "Phoenix Suns": {
    logo: "../images/logos/Suns.svg",
    primaryColor: "#1d1160",
    secondaryColor: "#e56020",
    thirdColor: "#63727a",
  }, 
  "Sacramento Kings": {
    logo: "../images/logos/Kings.svg",
    primaryColor: "#5a2d81",
    secondaryColor: "#63727a",
    thirdColor: "#ffffff",
  },  
  "Memphis Grizzlies": {
    logo: "../images/logos/Grizzlies.svg",
    primaryColor: "#23375b",
    secondaryColor: "#5d76a9",
    thirdColor: "#12173f",
  },
  "New Orleans Pelicans": {
    logo: "../images/logos/Pelicans.svg",
    primaryColor: "#002b5c",
    secondaryColor: "#b4975a",
    thirdColor: "#e31837",
  },
  "San Antonio Spurs": {
    logo: "../images/logos/Spurs.svg",
    primaryColor: "#c4ced3",
    secondaryColor: "#000000",
    thirdColor: "#63727a",
  },
  "Denver Nuggets": {
    logo: "../images/logos/Nuggets.svg",
    primaryColor: "#0e2240",
    secondaryColor: "#fec524",
    thirdColor: "#8b2131",
  },
  "Minnesota Timberwolves": {
    logo: "../images/logos/Timberwolves.svg",
    primaryColor: "#0c2340",
    secondaryColor: "#78be20",
    thirdColor: "#9ea2a2",
  },
  "Oklahoma City Thunder": {
    logo: "../images/logos/Thunder.svg",
    primaryColor: "#007ac1",
    secondaryColor: "#f05133",
    thirdColor: "#bec0c2",
  },
  "Orlando Magic": {
    logo: "../images/logos/Magic.svg",
    primaryColor: "#0077c0",
    secondaryColor: "#c4ced3",
    thirdColor: "#000000",
  },
  "Philadelphia 76ers": {
    logo: "../images/logos/76ers.svg",
    primaryColor: "#ed174c",
    secondaryColor: "#006bb6",
    thirdColor: "#002b5c",
  },
  "Phoenix Suns": {
    logo: "../images/logos/Suns.svg",
    primaryColor: "#1d1160",
    secondaryColor: "#e56020",
    thirdColor: "#63727a",
  },
  "Portland Trail Blazers": {
    logo: "../images/logos/Trailblazers.svg",
    primaryColor: "#e03a3e",
    secondaryColor: "#000000",
    thirdColor: "#ffffff",
  },
  "Sacramento Kings": {
    logo: "../images/logos/Kings.svg",
    primaryColor: "#5a2d81",
    secondaryColor: "#63727a",
    thirdColor: "#000000",
  }, 
  "Toronto Raptors": {
    logo: "https://cdn.nba.com/logos/nba/tor.svg",
    primaryColor: "#ce1141",
    secondaryColor: "#000000",
    thirdColor: "#ffffff",
  },
  "Utah Jazz": {
    logo: "../images/logos/Jazz.svg",
    primaryColor: "#002b5c",
    secondaryColor: "#00471b",
    thirdColor: "#f9a01b",
  },
  "Washington Wizards": {
    logo: "../images/logos/Wizards.svg",
    primaryColor: "#002b5c",
    secondaryColor: "#e31837",
    thirdColor: "#c4ced3",
  },
  "New York Knicks": {
    logo: "../images/logos/Knicks.svg",
    primaryColor: "#006bb6",
    secondaryColor: "#f58426",
    thirdColor: "#ffffff",
  },
};
